# Generated by Django 4.1 on 2022-08-14 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(blank=True)),
                ('gender', models.TextField(blank=True)),
                ('type_of_profile', models.IntegerField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('profile_of', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of', models.IntegerField(blank=True, null=True)),
                ('collaborators', models.ManyToManyField(blank=True, null=True, related_name='colaborators', to='publisher.userprofile')),
                ('files', models.ManyToManyField(blank=True, null=True, related_name='files', to='publisher.fileholder')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publisher.userprofile')),
            ],
        ),
    ]
